image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
    - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - ssh-keygen -t rsa -b 2048 -f tf-key-pair -N ""
    - terraform --version
    - terraform init

stages:
    - validate
    - plan
    - apply
    - destroy

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    dependencies:
        - validate
    script:
        - terraform plan -out "planfile"
    artifacts:
        paths:
            - planfile

apply:
    stage: apply
    dependencies:
        - plan
    script:
        - terraform apply -auto-approve
    when: manual
    
destroy:
    stage: destroy
    script:
        - terraform destroy -auto-approve
    when: manual

